//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoCompany.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourtDistrict
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourtDistrict()
        {
            this.CourtLocations = new HashSet<CourtLocation>();
        }
    
        public int Id { get; set; }
        public string Name { get; private set; }
        public string WebSite { get; private set; }
        public int RegionId { get; set; }
    
        public virtual CourtRegion CourtRegion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourtLocation> CourtLocations { get; set; }
    }
}
