//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoCompany.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourtRegion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourtRegion()
        {
            this.CourtDistricts = new HashSet<CourtDistrict>();
        }
    
        public int Id { get; set; }
        public string Name { get; private set; }
        public string Number { get; private set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourtDistrict> CourtDistricts { get; set; }
    }
}
