//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoCompany.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoCompany.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; value for node &apos;{1}&apos; is not found.
        /// </summary>
        internal static string Error_AttributeIsNotFound {
            get {
                return ResourceManager.GetString("Error_AttributeIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find districts table on page &apos;{0}&apos;..
        /// </summary>
        internal static string Error_DistrictsTableFail {
            get {
                return ResourceManager.GetString("Error_DistrictsTableFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load web page - {0}. \r\n Url - &apos;{1}&apos;, attempt - &apos;{2}&apos; from &apos;{3}&apos;..
        /// </summary>
        internal static string Error_FailedLoadPageRetry {
            get {
                return ResourceManager.GetString("Error_FailedLoadPageRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load districts for particular region &apos;{0}&apos;. Url - &apos;{1}&apos;..
        /// </summary>
        internal static string Error_FailedToLoadDistricts {
            get {
                return ResourceManager.GetString("Error_FailedToLoadDistricts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load main page..
        /// </summary>
        internal static string Error_FailedToLoadMainPage {
            get {
                return ResourceManager.GetString("Error_FailedToLoadMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load regions..
        /// </summary>
        internal static string Error_FailedToLoadRegions {
            get {
                return ResourceManager.GetString("Error_FailedToLoadRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to locations page &apos;{0}&apos;..
        /// </summary>
        internal static string Error_FailedToLocationsPage {
            get {
                return ResourceManager.GetString("Error_FailedToLocationsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL &apos;{0}&apos;..
        /// </summary>
        internal static string Error_InValidUrl {
            get {
                return ResourceManager.GetString("Error_InValidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find locations table on page &apos;{0}&apos;..
        /// </summary>
        internal static string Error_LocationsTableFail {
            get {
                return ResourceManager.GetString("Error_LocationsTableFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load locations territory. Page - &apos;{0}&apos;..
        /// </summary>
        internal static string Error_LocationsTerritoryFail {
            get {
                return ResourceManager.GetString("Error_LocationsTerritoryFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node &apos;{0}&apos; is not found..
        /// </summary>
        internal static string Error_NodeIsNotFound {
            get {
                return ResourceManager.GetString("Error_NodeIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip page - &apos;{0}&apos;..
        /// </summary>
        internal static string Error_SkipPage {
            get {
                return ResourceManager.GetString("Error_SkipPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load all curt regions..
        /// </summary>
        internal static string Trace_AllCurtRegionsLoad {
            get {
                return ResourceManager.GetString("Trace_AllCurtRegionsLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading HTML document ({0})..
        /// </summary>
        internal static string Trace_HtmlLoad {
            get {
                return ResourceManager.GetString("Trace_HtmlLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load districts for region &apos;{0}&apos;..
        /// </summary>
        internal static string Trace_LoadDistrictsForRegion {
            get {
                return ResourceManager.GetString("Trace_LoadDistrictsForRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load locations ({0})..
        /// </summary>
        internal static string Trace_LoadLocations {
            get {
                return ResourceManager.GetString("Trace_LoadLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Districts saving..
        /// </summary>
        internal static string Trace_SaveDistricts {
            get {
                return ResourceManager.GetString("Trace_SaveDistricts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations saving..
        /// </summary>
        internal static string Trace_SaveLocations {
            get {
                return ResourceManager.GetString("Trace_SaveLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions saving..
        /// </summary>
        internal static string Trace_SaveRegions {
            get {
                return ResourceManager.GetString("Trace_SaveRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage cleaning..
        /// </summary>
        internal static string Trace_StorageCleaning {
            get {
                return ResourceManager.GetString("Trace_StorageCleaning", resourceCulture);
            }
        }
    }
}
